// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiskOfRain.DataContext;

#nullable disable

namespace RiskOfRain.DataContext.Migrations
{
    [DbContext(typeof(RiskOfRainContext))]
    [Migration("20250129142712_SeedData2")]
    partial class SeedData2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RiskOfRain.Model.Attaque", b =>
                {
                    b.Property<int>("IdAttaque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAttaque"));

                    b.Property<int>("CoutPointCombat")
                        .HasColumnType("int");

                    b.Property<int>("Magie")
                        .HasColumnType("int");

                    b.Property<string>("NomAttaque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Physique")
                        .HasColumnType("int");

                    b.HasKey("IdAttaque");

                    b.ToTable("Attaques");

                    b.HasData(
                        new
                        {
                            IdAttaque = 1,
                            CoutPointCombat = 5,
                            Magie = 0,
                            NomAttaque = "Charge",
                            Physique = 40
                        },
                        new
                        {
                            IdAttaque = 2,
                            CoutPointCombat = 15,
                            Magie = 65,
                            NomAttaque = "FireBall",
                            Physique = 0
                        },
                        new
                        {
                            IdAttaque = 3,
                            CoutPointCombat = 10,
                            Magie = 0,
                            NomAttaque = "FirePunch",
                            Physique = 60
                        });
                });

            modelBuilder.Entity("RiskOfRain.Model.AttaqueMonstre", b =>
                {
                    b.Property<int>("IdAttaqueMonstre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAttaqueMonstre"));

                    b.Property<int>("IdAttaque")
                        .HasColumnType("int");

                    b.Property<int>("IdMonstre")
                        .HasColumnType("int");

                    b.HasKey("IdAttaqueMonstre");

                    b.HasIndex("IdAttaque");

                    b.HasIndex("IdMonstre");

                    b.ToTable("AttaqueMonstre");

                    b.HasData(
                        new
                        {
                            IdAttaqueMonstre = 1,
                            IdAttaque = 1,
                            IdMonstre = 1
                        },
                        new
                        {
                            IdAttaqueMonstre = 2,
                            IdAttaque = 2,
                            IdMonstre = 1
                        });
                });

            modelBuilder.Entity("RiskOfRain.Model.Monstre", b =>
                {
                    b.Property<int>("IdMonstre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMonstre"));

                    b.Property<string>("CouleurMonstre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomMonstre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PointCombatMonstre")
                        .HasColumnType("int");

                    b.Property<int>("PvMaxMonstre")
                        .HasColumnType("int");

                    b.Property<int>("PvMonstre")
                        .HasColumnType("int");

                    b.Property<string>("TypeMonstre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMonstre");

                    b.ToTable("Monstres");

                    b.HasData(
                        new
                        {
                            IdMonstre = 1,
                            CouleurMonstre = "Rouge",
                            NomMonstre = "Alpha Construct",
                            PointCombatMonstre = 55,
                            PvMaxMonstre = 0,
                            PvMonstre = 125,
                            TypeMonstre = "Mutant"
                        },
                        new
                        {
                            IdMonstre = 2,
                            CouleurMonstre = "Bleu",
                            NomMonstre = "Alloy Vulture",
                            PointCombatMonstre = 120,
                            PvMaxMonstre = 0,
                            PvMonstre = 180,
                            TypeMonstre = "Mage"
                        });
                });

            modelBuilder.Entity("RiskOfRain.Model.AttaqueMonstre", b =>
                {
                    b.HasOne("RiskOfRain.Model.Attaque", "Attaque")
                        .WithMany("AttaqueMonstre")
                        .HasForeignKey("IdAttaque")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiskOfRain.Model.Monstre", "Monstre")
                        .WithMany("AttaqueMonstre")
                        .HasForeignKey("IdMonstre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attaque");

                    b.Navigation("Monstre");
                });

            modelBuilder.Entity("RiskOfRain.Model.Attaque", b =>
                {
                    b.Navigation("AttaqueMonstre");
                });

            modelBuilder.Entity("RiskOfRain.Model.Monstre", b =>
                {
                    b.Navigation("AttaqueMonstre");
                });
#pragma warning restore 612, 618
        }
    }
}
